title:        MineR.矿工
tagline:      "勤劳的矿工一直在挖矿"
url:          http://www.zuohaisu.cn
author:
  name:       "Haisu Zuo"
  email:      "zuohaisu@gmail.com"
  avatar:     ""
markdown:     rdiscount
permalink: /posts/:title
pygments:     true
paginate:     5
disqus_name: minerzhs