title:        MineR.矿工
tagline:      "勤劳的矿工一直在挖矿"
url:          http://www.zuohaisu.cn
author:
  name:       "Haisu Zuo"
  email:      "zuohaisu@gmail.com"
  avatar:     "http://a.disquscdn.com/uploads/users/9045/3987/avatar92.jpg?1389630492"
markdown:     rdiscount
permalink: /posts/:title
pygments:     true
paginate:     5
disqus_name: minerzhs